spring:
  application:
    name: mall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 47.98.187.212:8848
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: 47.98.187.212
  session:
    store-type: redis

server:
  port: 20000
